[project]
name = "fastoai"
version = "1.0.2"
description = "Start an API server as OpenAI's"
authors = [
    { name = "Tang Ziya", email = "tcztzy@gmail.Com" }
]
dependencies = [
    "aiosqlite>=0.20.0",
    "anthropic>=0.40.0",
    "anyio[trio]>=4.7.0",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.111.0",
    "openai>=1.57.0",
    "pydantic[email]>=2.9.2",
    "pydantic-settings>=2.6.1",
    "ruff>=0.8.2",
    "sqlalchemy[asyncio]>=2.0.32",
    "sqlmodel>=0.0.22",
]
readme = "README.md"
requires-python = ">= 3.11"

[project.scripts]
fastoai = "fastoai.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/fastoai"]
artifacts = [
    "*.yaml",
    "*.json",
]

[tool.ruff]
extend-exclude = ["generated"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
venvPath = "."
venv = ".venv"
ignore = ["**/generated/**"]
