[project]
name = "fastoai"
version = "1.0.2"
description = "Start an API server as OpenAI's"
authors = [
    { name = "Tang Ziya", email = "tcztzy@gmail.Com" }
]
dependencies = [
    "openai>=1.55.0",
    "fastapi[standard]>=0.115.5",
    "pydantic[email]>=2.10.1",
    "pydantic-settings>=2.6.1",
    "ruff>=0.8.0",
    "sqlmodel>=0.0.22",
    "aiosqlite>=0.20.0",
    "asyncpg>=0.30.0",
    "sqlalchemy[asyncio]>=2.0.36",
    "pyyaml>=6.0.2",
    "fsspec[github]>=2024.10.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/fastoai"]
artifacts = [
    "*.yaml",
    "*.json",
    "cache",
    "d910ba2ef878f7db0223a966b81c8b3f3b65027bb39e4431bb05140171eece39",
]

[tool.ruff]
extend-exclude = ["generated"]

[tool.ruff.lint]
extend-select = ["I"]
