[project]
name = "fastoai"
version = "1.0.2"
description = "Start an API server as OpenAI's"
authors = [
    { name = "Tang Ziya", email = "tcztzy@gmail.Com" }
]
dependencies = [
    "openai>=1.42.0",
    "fastapi[standard]>=0.112.0",
    "pydantic[email]>=2.8.2",
    "pydantic-settings>=2.4.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[project.optional-dependencies]
ollama = ["ollama>=0.3.1"]
beta = [
    "orjson>=3.10.7",
    "sqlmodel>=0.0.21",
]
anthropic = [
    "anthropic>=0.34.1",
]
google-generativeai = [
    "google-generativeai>=0.7.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/fastoai"]

[tool.ruff.lint]
extend-select = ["I"]
